name: flutter_airpods
description: A Library for accessing AirPods data via CMHeadphoneMotionManager. Simplifies retrieval of information about currently connected AirPods.
version: 1.0.5
repository: https://github.com/lucas-goldner/flutter_airpods
issue_tracker: https://github.com/lucas-goldner/flutter_airpods/issues

environment:
  sdk: ">=2.18.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAirpodsPlugin
